const worldChampions = [
  "Lewis Hamilton",
  "Michael Schumacher",
  "Juan Manuel Fangio",
  "Alain Prost",
  "Nelson Piquet",
  "Jackie Stewart",
  "Jim Clark",
  "Niki Lauda",
  "Mario Andretti",
  "Jack Brabham",
  "Emerson Fittipaldi",
  "Mika Hakkinen",
  "Keke Rosberg",
  "Sebastian Vettel",
  "Fernando Alonso",
  "Nigel Mansell",
  "Graham Hill",
  "James Hunt",
  "Ayrton Senna",
  "Kimi Raikkonen",
  "Max Verstappen",
  "Damon Hill",
  "Jochen Rindt",
  "Giuseppe Farina",
  "Alberto Ascari",
  "Mike Hawthorn",
  "Phil Hill",
  "John Surtees",
  "Jody Scheckter",
  "Jacques Villeneuve",
  "Nico Rosberg",
  "Jenson Button",
];

const ferrari = [
  "Sebastian Vettel",
  "Charles Leclerc",
  "Carlos Sainz",
  "Kimi Raikkonen",
  "Fernando Alonso",
  "Michael Schumacher",
  "Felipe Massa",
  "Rubens Barrichello",
  "Eddie Irvine",
  "Gerhard Berger",
  "Jean Alesi",
  "Nigel Mansell",
  "Alain Prost",
  "Michele Alboreto",
  "Rene Arnoux",
  "Jody Scheckter",
  "Gilles Villeneuve",
  "Niki Lauda",
  "Clay Regazzoni",
  "Jacky Ickx",
  "John Surtees",
  "Lorenzo Bandini",
  "Wolfgang von Trips",
  "Phil Hill",
  "Mike Hawthorn",
  "Alberto Ascari",
  "Philippe Alliot",
  "Teo Fabi",
  "Mauro Forghieri",
  "Giancarlo Fisichella",
  "Emerson Fittipaldi",
  "Luigi Musso",
  "Eugenio Castellotti",
  "Giovanni Bracco",
  "Giuseppe Farina",
  "Michele Alboreto",
  "John Love",
  "Clyde McCormick",
  "Bob Gerard",
  "Raymond Sommer",
  "Roberto Lippi",
  "Luca Badoer",
  "Ludovico Scarfiotti",
  "Nino Farina",
  "Piero Taruffi",
  "Alessandro Nannini",
  "Oliviero Gatti",
  "Nino Vaccarella",
  "Rui Patricio",
  "Beppe Gabbiani",
  "Dario Benuzzi",
  "Emilio Giuseppe",
  "Alessandro de Tomaso",
  "Luigi Taramazzo",
  "Serge Kormann",
  "Ettore Bracca",
  "Gino Munaron",
  "Franco Cortese",
  "Giorgio Scarlatti",
  "Maurizio Sandro",
  "Vittorio Brambilla",
  "Jacques Villeneuve",
  "Alberto Ascari",
  "Juan Manuel Fangio",
  "Tommy Byrne",
  "Kurt Ahrens",
  "Ronnie Peterson",
  "Fernando Peixoto",
  "Carlos Reutemann",
  "Jacques Laffite",
  "Paul Frere",
];

const mclaren = [
  "Bruce McLaren",
  "Denny Hulme",
  "Chris Amon",
  "John Surtees",
  "Peter Gethin",
  "Mike Donnelly",
  "Emerson Fittipaldi",
  "James Hunt",
  "Niki Lauda",
  "John Watson",
  "Alain Prost",
  "Mika Hakkinen",
  "David Coulthard",
  "Kimi Raikkonen",
  "Fernando Alonso",
  "Lewis Hamilton",
  "Jenson Button",
  "Sergio Pérez",
  "Kevin Magnussen",
  "Stoffel Vandoorne",
  "Lando Norris",
  "Oscar Piastri",
  "Riccardo Patrese",
  "Martin Brundle",
  "Michael Andretti",
  "Jean Alesi",
  "Mika Salo",
  "Takuma Sato",
  "Oliver Turvey",
  "Max Chilton",
  "Paul di Resta",
  "Daniel Ricciardo",
  "Carlos Sainz",
];

const redBull = [
  "Mika Salo",
  "Jan Magnussen",
  "Johnny Herbert",
  "Tommy Byrne",
  "Barrichello",
  "Stefan Johansson",
  "Michele Alboreto",
  "David Coulthard",
  "Christian Klien",
  "Robert Doornbos",
  "Mark Webber",
  "Sebastian Vettel",
  "Daniel Ricciardo",
  "Max Verstappen",
  "Pierre Gasly",
  "Alex Albon",
  "Sergio Pérez",
  "Liam Lawson",
];

const mercedes = [
  "Jacques Villeneuve",
  "Ricardo Zonta",
  "Olivier Panis",
  "Jenson Button",
  "Takuma Sato",
  "Anthony Davidson",
  "David Coulthard",
  "Narain Karthikeyan",
  "Sébastien Bourdais",
  "Jackie Stewart",
  "François Cevert",
  "Chris Amon",
  "Jean-Pierre Beltoise",
  "Patrick Depailler",
  "Jody Scheckter",
  "Lella Lombardi",
  "Tom Pryce",
  "Jean-Pierre Jarier",
  "Riccardo Patrese",
  "Mika Salo",
  "Damon Hill",
  "Jenson Button",
  "Rubens Barrichello",
  "Kimi Raikkonen",
  "Timo Glock",
  "Heikki Kovalainen",
  "Kamui Kobayashi",
  "Jenson Button",
  "Rubens Barrichello",
  "Nick Heidfeld",
  "Michael Schumacher",
  "Nico Rosberg",
  "Lewis Hamilton",
  "Valtteri Bottas",
  "George Russell",
];

const williams = [
  "Alan Jones",
  "Clay Regazzoni",
  "Carlos Reutemann",
  "Keke Rosberg",
  "Jacques Laffite",
  "Nigel Mansell",
  "Nelson Piquet",
  "Riccardo Patrese",
  "Damon Hill",
  "Jacques Villeneuve",
  "Ralf Schumacher",
  "Juan Pablo Montoya",
  "Mark Webber",
  "Nico Rosberg",
  "Valtteri Bottas",
  "Felipe Massa",
  "Lance Stroll",
  "Sergey Sirotkin",
  "Robert Kubica",
  "George Russell",
  "Nicholas Latifi",
  "Alexander Albon",
  "Logan Sargeant",
  "Carlos Sainz",
  "Ayrton Senna",
  "David Coulthard",
  "Mika Salo",
  "Tommy Byrne",
  "Stefan Johansson",
  "Michele Alboreto",
  "Taki Inoue",
];

const lotus = [
  "Ayrton Senna",
  "Jim Clark",
  "Nelson Piquet",
  "Mario Andretti",
  "Kimi Raikkonen",
  "Mika Hakkinen",
  "Romain Grosjean",
  "Heikki Kovalainen",
  "Jarno Trulli",
];

const renault = [
  "Fernando Alonso",
  "Nelson Piquet",
  "Jarno Trulli",
  "Giancarlo Fisichella",
  "Petrov Vitaly",
  "Robert Kubica",
  "Daniel Ricciardo",
  "Esteban Ocon",
];

const sauber = [
  "Karl Wendlinger",
  "JJ Lehto",
  "Heinz-Harald Frentzen",
  "Andrea de Cesaris",
  "Jean-Christophe Boullion",
  "Johnny Herbert",
  "Gianni Morbidelli",
  "Nicola Larini",
  "Norberto Fontana",
  "Pedro Diniz",
  "Giancarlo Fisichella",
  "Esteban Gutiérrez",
  "Marcus Ericsson",
  "Felipe Nasr",
  "Kamui Kobayashi",
  "Sergio Pérez",
  "Felipe Massa",
  "Nick Heidfeld",
  "Adrian Sutil",
  "Pascal Wehrlein",
  "Charles Leclerc",
  "Antonio Giovinazzi",
  "Robert Kubica",
  "Valtteri Bottas",
  "Zhou Guanyu",
  "Théo Pourchaire",
  "Zane Maloney",
  "Nico Hülkenberg",
  "Gabriel Bortoleto",
];

const haas = [
  "Romain Grosjean",
  "Kevin Magnussen",
  "Nico Hülkenberg",
  "Mick Schumacher",
  "Esteban Gutiérrez",
  "Gio Ricciardo",
  "Pastor Maldonado",
];

const astonMartin = [
  "Sebastian Vettel",
  "Lance Stroll",
  "Sergio Pérez",
  "Esteban Ocon",
  "Nico Hülkenberg",
  "Robert Kubica",
  "Adrian Sutil",
  "Paul di Resta",
  "Vitantonio Liuzzi",
  "Karun Chandhok",
];

const hondaTeams = [
  "Jenson Button",
  "Rubens Barrichello",
  "Takuma Sato",
  "Ralf Schumacher",
  "Olivier Panis",
  "Christian Klien",
  "Alex Wurz",
];

const winnersWithoutTitles = [
  "Jenson Button",
  "Mark Webber",
  "Juan Pablo Montoya",
  "Romain Grosjean",
  "Robert Kubica",
  "Daniel Ricciardo",
  "Sergio Pérez",
];

const williams1990s = [
  "Damon Hill",
  "Jacques Villeneuve",
  "Alain Prost",
  "Nigel Mansell",
];

const raceStarts300 = [
  "Kimi Raikkonen",
  "Michael Schumacher",
  "Fernando Alonso",
  "Lewis Hamilton",
];

const multipleMonzaWinners = [
  "Ayrton Senna",
  "Michael Schumacher",
  "Lewis Hamilton",
];

const homeGPWinners = [
  "Lewis Hamilton",
  "Fernando Alonso",
  "Sebastian Vettel",
  "Charles Leclerc",
  "Max Verstappen",
];

const securedTitleFinalRace = [
  "Lewis Hamilton",
  "Michael Schumacher",
  "Fernando Alonso",
  "Max Verstappen",
];

const britishGPWinnersForBritishTeams = [
  "Lewis Hamilton",
  "Nigel Mansell",
  "David Coulthard",
];

const midSeasonDebuts = [
  "Carlos Sainz",
  "Daniel Ricciardo",
  "Sebastian Vettel",
];

const grandSlamAchievers = [
  "Jim Clark",
  "Ayrton Senna",
  "Lewis Hamilton",
  "Sebastian Vettel",
];

const reserveRoleDrivers = [
  "Robert Kubica",
  "Jenson Button",
  "Mick Schumacher",
];

export const categories: Record<string, string[]> = {
  "World Champions": worldChampions,
  Ferrari: ferrari,
  McLaren: mclaren,
  RedBull: redBull,
  Mercedes: mercedes,
  Williams: williams,
  Lotus: lotus,
  Renault: renault,
  Sauber: sauber,
  Haas: haas,
  "Aston Martin": astonMartin,
  "Honda Teams": hondaTeams,
  "Winners without Titles": winnersWithoutTitles,
  "Williams 1990s": williams1990s,
  "300 Race Starts": raceStarts300,
  "Won Monza Multiple Times": multipleMonzaWinners,
  "Home GP Winners": homeGPWinners,
  "Secured Title in the Final Race": securedTitleFinalRace,
  "British GP Winners for British Team": britishGPWinnersForBritishTeams,
  "Mid Season Debuts": midSeasonDebuts,
  "Grand Slam Achievers": grandSlamAchievers,
  "Reserve Role Drivers": reserveRoleDrivers,
};

const allDrivers = [
  ...worldChampions,
  ...ferrari,
  ...mclaren,
  ...redBull,
  ...mercedes,
  ...williams,
  ...lotus,
  ...renault,
  ...sauber,
  ...haas,
  ...astonMartin,
  ...hondaTeams,
  ...winnersWithoutTitles,
  ...williams1990s,
  ...raceStarts300,
  ...multipleMonzaWinners,
  ...homeGPWinners,
  ...securedTitleFinalRace,
  ...britishGPWinnersForBritishTeams,
  ...midSeasonDebuts,
  ...grandSlamAchievers,
  ...reserveRoleDrivers,
];

export const drivers = [...new Set(allDrivers)];
export const lastUpdated = "18.01.2025";
